### ISSUE TITLE
Error 500 when loading app in iframe

### ISSUE THREAD

**Issue by spiral6** [rmountjoy92/DashMachine#108]
```python
[2020-04-06 12:07:42,594] ERROR in app: Exception on /app_view?1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: app_view() missing 1 required positional argument: 'app_id'
```

On qBittorrents's Web UI, clickjacking and CSRF protection have been disabled. ~~This used to work but no longer does.~~ None of the apps I add that use iframes are working.

**Comment by marcjmiller** [comment]
This works fine for me.  Perhaps you are on an old version?  Could you paste the config for one of the apps that aren't working for you so I could try it?

**Comment by rmountjoy92** [comment]
this was fixed in https://github.com/rmountjoy92/DashMachine/commit/170daf1b81aa3615d3a95db78bb2ff8395cdda3d

**Comment by spiral6** [comment]
Can confirm, updated image and it does now work. Thanks a lot.
