### ISSUE TITLE
Error on restart

### ISSUE THREAD

**Issue by arejaytee** [rmountjoy92/DashMachine#158]
[2020-04-27 11:06:51 +1000] [8] [ERROR] Exception in worker process

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
mod = importlib.import_module(module)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/dashmachine/wsgi.py", line 15, in <module>
dashmachine_init()
File "/dashmachine/dashmachine/main/utils.py", line 59, in dashmachine_init
read_config()
File "/dashmachine/dashmachine/main/read_config.py", line 228, in read_config
tag_json = json.loads(tag_setting)
File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-04-27 11:06:51 +1000] [8] [INFO] Worker exiting (pid: 8)
[2020-04-27 11:06:51 +1000] [1] [INFO] Shutting down: Master
[2020-04-27 11:06:51 +1000] [1] [INFO] Reason: Worker failed to boot.

**Comment by Hampusm** [comment]
I have the same problem #159

**Comment by rmountjoy92** [comment]
there is an issue with your 
`tags = `
setting in Settings. Tag settings must be entered exactly like so:
`tags = {"name": "House", "icon": "home", "sort_pos": 1},{"name": "Tools", "icon": "build", "sort_pos": 3},{"name": "Files", "icon": "folder", "sort_pos": 4}`
