### ISSUE TITLE
Icon not loading on dashboard; throwing Flask errors

### ISSUE THREAD

**Issue by bradleyfrank** [rmountjoy92/DashMachine#164]
I tried to add the following app:

```
[1Password]
prefix = https://
url = myaccount.1password.com
icon = static/images/apps/1password.png
sidebar_icon = static/images/apps/1password.png
description = 1Password vault
open_in = new_tab
tags = home, utilities
groups = users
```

I added the icon to the proper location (I have a couple dozen icons there already that are working fine):

```
root@server:/path/to/dashmachine/icons# pwd
/path/to/dashmachine/icons
root@server:/nas0/appdata/dashmachine/icons# ll
total 210
drwxr-xr-x 2 root root    25 May 15 11:09 ./
drwxr-xr-x 5 root root     9 May 15 11:13 ../
-rw-r--r-- 1 root root 14062 May 15 11:09 1password.png
```

After clicking 'Save' on the config screen, I reload the dashboard and see the broken image:

https://imgur.com/9UMQYCQ

I thought maybe I had to reload the container, but I'm getting Python Flask errors now:

```
root@server:/path/to/dashmachine# docker-compose up -d
Starting dashmachine ...
Starting dashmachine ... done
root@server:/path/to/dashmachine# docker logs dashmachine
[2020-05-14 09:13:47 -0400] [1] [INFO] Starting gunicorn 20.0.4
[2020-05-14 09:13:47 -0400] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-05-14 09:13:47 -0400] [1] [INFO] Using worker: sync
[2020-05-14 09:13:47 -0400] [7] [INFO] Booting worker with pid: 7
[2020-05-14 09:24:48,974] ERROR in app: Exception on /settings/add_images [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/dashmachine/dashmachine/settings_system/routes.py", line 77, in add_images
    new_path = os.path.join(dest_folder, file.name)
AttributeError: 'NoneType' object has no attribute 'name'
[2020-05-14 11:33:12,588] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/dashmachine/dashmachine/main/routes.py", line 45, in home
    if not check_groups(settings.home_access_groups, current_user):
  File "/dashmachine/dashmachine/main/utils.py", line 71, in check_groups
    for group_role in group.roles.split(","):
AttributeError: 'NoneType' object has no attribute 'roles'
[2020-05-14 11:33:16,947] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/dashmachine/dashmachine/main/routes.py", line 45, in home
    if not check_groups(settings.home_access_groups, current_user):
  File "/dashmachine/dashmachine/main/utils.py", line 71, in check_groups
    for group_role in group.roles.split(","):
AttributeError: 'NoneType' object has no attribute 'roles'
[2020-05-14 11:33:17,875] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/dashmachine/dashmachine/main/routes.py", line 45, in home
    if not check_groups(settings.home_access_groups, current_user):
  File "/dashmachine/dashmachine/main/utils.py", line 71, in check_groups
    for group_role in group.roles.split(","):
AttributeError: 'NoneType' object has no attribute 'roles'
[2020-05-15 11:07:45 -0400] [1] [INFO] Handling signal: term
[2020-05-15 11:07:45 -0400] [7] [INFO] Worker exiting (pid: 7)
[2020-05-15 11:07:45 -0400] [1] [INFO] Shutting down: Master
[2020-05-15 11:07:59 -0400] [1] [INFO] Starting gunicorn 20.0.4
[2020-05-15 11:07:59 -0400] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-05-15 11:07:59 -0400] [1] [INFO] Using worker: sync
[2020-05-15 11:07:59 -0400] [7] [INFO] Booting worker with pid: 7
```

**Comment by bradleyfrank** [comment]
Somehow got the path wrong in the config file. Not a bug.
