### ISSUE TITLE
Issue with VS Code icon?

### ISSUE THREAD

**Issue by mtverlee** [rmountjoy92/DashMachine#191]
Hello,

I'm running `rmountjoy/dashmachine:latest@sha256:378f94c97ffc3dcd3acced5f3e62da63a6b1370fa6509ec8032a20fdb3e5d55e` on my Debian 10 docker host on Google Cloud. Today I noticed my DashMachine instance is down and the logs show the following error. 

`
[2020-07-10 23:06:42 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-07-10 23:06:42 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-07-10 23:06:42 +0000] [1] [INFO] Using worker: sync
[2020-07-10 23:06:42 +0000] [7] [INFO] Booting worker with pid: 7
[2020-07-10 23:06:44 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/dashmachine/wsgi.py", line 15, in <module>
    dashmachine_init()
  File "/dashmachine/dashmachine/main/utils.py", line 34, in dashmachine_init
    resize_template_app_images()
  File "/dashmachine/dashmachine/main/utils.py", line 101, in resize_template_app_images
    image = Image.open(fp)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2895, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/dashmachine/dashmachine/static/images/apps/vscode.png'
[2020-07-10 23:06:44 +0000] [7] [INFO] Worker exiting (pid: 7)
[2020-07-10 23:06:44 +0000] [1] [INFO] Shutting down: Master
[2020-07-10 23:06:44 +0000] [1] [INFO] Reason: Worker failed to boot.
`

I don't have any entries for any sort of VS Code app in my `config.ini` app and trying to mess around in the container using `docker exec -it dashmachine /bin/bash` fails because the container is constantly restarting.

Not sure if this is a bug or specific to me but do you have any ideas on what to do to fix it? I'm semi-new to docker and I'm not sure what to do. Thanks!

**Comment by mtverlee** [comment]
Upon further investigation, I was able to resolve this issue by stopping/deleting my container and creating a new one. I guess my container was just borked. I'll close this issue and if devs think this is a bug they're welcome to re-open it.
