### ISSUE TITLE
Latest Docker update seems to have broke ARM V7 image

### ISSUE THREAD

**Issue by UtopiaOpera** [rmountjoy92/DashMachine#226]
Docker updated yesterday and now my dashmachine image fails 2 run. here is the output from log.

```
File "/dashmachine/dashmachine/main/utils.py", line 34, in dashmachine_init
    resize_template_app_images()
  File "/dashmachine/dashmachine/main/utils.py", line 101, in resize_template_app_images
    image = Image.open(fp)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2943, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/dashmachine/dashmachine/static/images/apps/docker.png'
[2022-03-25 08:09:28 +0000] [8] [INFO] Worker exiting (pid: 8)
[2022-03-25 08:09:28 +0000] [1] [INFO] Shutting down: Master
[2022-03-25 08:09:28 +0000] [1] [INFO] Reason: Worker failed to boot.
[2022-03-25 08:09:36 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2022-03-25 08:09:36 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2022-03-25 08:09:36 +0000] [1] [INFO] Using worker: sync
[2022-03-25 08:09:36 +0000] [8] [INFO] Booting worker with pid: 8
[2022-03-25 08:09:41 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/dashmachine/wsgi.py", line 15, in <module>
    dashmachine_init()
  File "/dashmachine/dashmachine/main/utils.py", line 34, in dashmachine_init
    resize_template_app_images()
  File "/dashmachine/dashmachine/main/utils.py", line 101, in resize_template_app_images
    image = Image.open(fp)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2943, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/dashmachine/dashmachine/static/images/apps/docker.png'
[2022-03-25 08:09:41 +0000] [8] [INFO] Worker exiting (pid: 8)
[2022-03-25 08:09:41 +0000] [1] [INFO] Shutting down: Master
[2022-03-25 08:09:41 +0000] [1] [INFO] Reason: Worker failed to boot.
[2022-03-25 08:09:47 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2022-03-25 08:09:47 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2022-03-25 08:09:47 +0000] [1] [INFO] Using worker: sync
[2022-03-25 08:09:47 +0000] [8] [INFO] Booting worker with pid: 8
[2022-03-25 08:09:52 +0000] [8] [ERROR] Exception in worker process

[2022-03-25 08:10:00 +0000] [8] [INFO] Booting worker with pid: 8

```

**Comment by UtopiaOpera** [comment]
Seems to have sorted it self out, since the update the port number were affected is my best guess.
