### ISSUE TITLE
BUG: Dashboard doesn't start

### ISSUE THREAD

**Issue by bijsven** [rmountjoy92/DashMachine#233]
I got an error about Python

 [2022-12-27 13:03:37 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
 

 [2022-12-27 13:03:50 +0000] [8] [INFO] Worker exiting (pid: 8)
 

 [2022-12-27 13:04:06 +0000] [9] [INFO] Booting worker with pid: 9
 

 [2022-12-27 13:04:31 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9)
 

 [2022-12-27 13:04:31 +0000] [9] [INFO] Worker exiting (pid: 9)
 

 [2022-12-27 13:04:32 +0000] [10] [INFO] Booting worker with pid: 10
 

 [2022-12-27 13:05:02 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
 

 [2022-12-27 13:05:02 +0000] [10] [INFO] Worker exiting (pid: 10)
 

 [2022-12-27 13:05:03 +0000] [11] [INFO] Booting worker with pid: 11
 

 [2022-12-27 13:05:24 +0000] [11] [ERROR] Socket error processing request.
 

 Traceback (most recent call last):
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 133, in handle
 

     req = next(parser)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/parser.py", line 41, in __next__
 

     self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 186, in __init__
 

     super().__init__(cfg, unreader)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 53, in __init__
 

     unused = self.parse(self.unreader)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 235, in parse
 

     self.headers = self.parse_headers(data[:idx])
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 73, in parse_headers
 

     remote_addr = self.unreader.sock.getpeername()
 

 OSError: [Errno 107] Transport endpoint is not connected
 

 [2022-12-27 13:05:24 +0000] [11] [ERROR] Socket error processing request.
 

 Traceback (most recent call last):
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 133, in handle
 

     req = next(parser)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/parser.py", line 41, in __next__
 

     self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 186, in __init__
 

     super().__init__(cfg, unreader)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 53, in __init__
 

     unused = self.parse(self.unreader)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 235, in parse
 

     self.headers = self.parse_headers(data[:idx])
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 73, in parse_headers
 

     remote_addr = self.unreader.sock.getpeername()
 

 OSError: [Errno 107] Transport endpoint is not connected
 

 [2022-12-27 13:05:24 +0000] [11] [ERROR] Socket error processing request.
 

 Traceback (most recent call last):
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 133, in handle
 

     req = next(parser)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/parser.py", line 41, in __next__
 

     self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
 

   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 186, in __init__

**Comment by derskythe** [comment]
I got:
```
dashmachine     | standard_init_linux.go:219: exec user process caused: exec format error
```
And the link to the full manual is dead, thanks to [WebArchive](https://web.archive.org/web/20200525012925/https://nashosted.com/manage-your-self-hosted-applications-using-dashmachine/)

The last commit was over 2 years ago, so I think this repository is dead.

RIP
