### ISSUE TITLE
DashMachine not working under subdomain, works fine from port

### ISSUE THREAD

**Issue by spiral6** [rmountjoy92/DashMachine#37]
Using DashMachine on a subdomain of my host (i.e. dashmachine.example.com) is not working fine, I get the following error in the logs:
```
[2020-03-16 03:56:10,242] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/dashmachine/dashmachine/main/routes.py", line 45, in check_valid_login
    request.endpoint.startswith("static"),
AttributeError: 'NoneType' object has no attribute 'startswith'
```
However, I don't get this error or anything like it when directly accessing DashMachine from the host and port. (i.e. example.com:5000)

**Comment by rmountjoy92** [comment]
Does this still happen using the latest version?

**Comment by JasonBucotte** [comment]
What does your proxy config look like? It's always worked as intended on my end

**Comment by spiral6** [comment]
I just updated to the latest version and I'm getting Error 405.
![image](https://user-images.githubusercontent.com/2887489/77927598-063ec480-726d-11ea-813f-acb9dde12fb4.png)


nginx.conf:
```nginx
upstream dashmachine {
    server 117.0.0.64:5000;
}
server {
        listen 80;
        listen [::]:80;
        server_name dashmachine.openmediavault.lan;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; object-src 'none'; media-src 'self' data:";
        gzip on;
        gzip_comp_level    5;
        gzip_min_length    256;
        gzip_proxied       any;
        gzip_vary          on;

        gzip_types
                application/javascript
                application/vnd.geo+json
                application/vnd.ms-fontobject
                application/x-font-ttf
                application/x-web-app-manifest+json
                font/opentype
                image/bmp
                image/svg+xml
                i       mage/x-icon
                text/cache-manifest
                text/css
                text/plain
                text/vcard
                text/vnd.rim.location.xloc
                text/vtt
                text/x-component
                text/x-cross-domain-policy;

        location / {
                #include /etc/nginx/funkwhale_proxy.conf;
                # global proxy conf
                proxy_set_header Host $host;
                #proxy_set_header X-Real-IP $remote_addr;
                #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #proxy_set_header X-Forwarded-Proto $scheme;
                #proxy_set_header X-Forwarded-Host $host:$server_port;
                #proxy_set_header X-Forwarded-Port $server_port;
                #proxy_redirect off;

                # websocket support
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                client_max_body_size 100M;
                proxy_pass   http://dashmachine/;
        }
}
```

**Comment by GetLiberated** [comment]
> What does your proxy config look like? It's always worked as intended on my end

can you share your proxy config?

**Comment by Mar16** [comment]
Here is my working proxy config, hopefully it helps you guys out
```
server {
    listen 443 ssl;
    server_name dash.domain.com;
    
    #SSL settings
    include /config/nginx/strong-ssl.conf;
    
    #Maxmind geoblock
    include /config/nginx/geoblock.conf;

location / {
        include /config/nginx/proxy.conf;
        proxy_pass http://LocalIP:Port;
        resolver 127.0.0.11 valid=30s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by spiral6** [comment]
@Mar16 This config is only partially helpful but it doesn't include `/config/nginx/proxy.conf` which is the proxy config presumably. It also does not define variables `LocalIP` or `Port` in the context of this `nginx.conf`.

**Comment by spiral6** [comment]
After updating DashMachine to the latest image, everything is working again as expected. I will go ahead and close this issue. 

I used this `nginx.conf` as my template.
```nginx
upstream dashmachine {
    server <IP>:5000;
}
server {
        listen 80;
        listen [::]:80;
        server_name dashmachine.example.com;

        location / {

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_pass   http://dashmachine/;
        }

}
```

**Comment by BadCo-NZ** [comment]
For anyone using LinuxServer.io's LetsEncrypt container on unraid, I found this proxy conf works (as LSio doesn't supply one).

`# make sure that your dns has a cname set for dashmachine

upstream dashmachine {
    server dashmachine:5000;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name your.domain.com;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        #enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app dashmachine;
        set $upstream_port 5000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
`
