### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 137: ordinal not in range(128)

### ISSUE THREAD

**Issue by nathanpalmer** [rmountjoy92/DashMachine#65]
I'm testing this out for the first time and running into an issue. I can't seem to modify settings, so I can't see much functionality so far.

- I pulled down the latest git
- installed the requirements
- python3 run.py

and when I got to settings I just see this. Thoughts?

```
Mar 28 17:38:22 redis gunicorn[8777]: [2020-03-28 17:38:22,058] ERROR in app: Exception on /settings [GET]
Mar 28 17:38:22 redis gunicorn[8777]: Traceback (most recent call last):
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
Mar 28 17:38:22 redis gunicorn[8777]:     response = self.full_dispatch_request()
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
Mar 28 17:38:22 redis gunicorn[8777]:     rv = self.handle_user_exception(e)
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 272, in error_router
Mar 28 17:38:22 redis gunicorn[8777]:     return original_handler(e)
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
Mar 28 17:38:22 redis gunicorn[8777]:     reraise(exc_type, exc_value, tb)
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
Mar 28 17:38:22 redis gunicorn[8777]:     raise value
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
Mar 28 17:38:22 redis gunicorn[8777]:     rv = self.dispatch_request()
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
Mar 28 17:38:22 redis gunicorn[8777]:     return self.view_functions[rule.endpoint](**req.view_args)
Mar 28 17:38:22 redis gunicorn[8777]:   File "/opt/dashmachine/dashmachine/settings_system/routes.py", line 42, in settings
Mar 28 17:38:22 redis gunicorn[8777]:     config.read(os.path.join(template_apps_folder, template_app_ini))
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/lib/python3.6/configparser.py", line 697, in read
Mar 28 17:38:22 redis gunicorn[8777]:     self._read(fp, filename)
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/lib/python3.6/configparser.py", line 1015, in _read
Mar 28 17:38:22 redis gunicorn[8777]:     for lineno, line in enumerate(fp, start=1):
Mar 28 17:38:22 redis gunicorn[8777]:   File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
Mar 28 17:38:22 redis gunicorn[8777]:     return codecs.ascii_decode(input, self.errors)[0]
Mar 28 17:38:22 redis gunicorn[8777]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 137: ordinal not in range(128)
```

**Comment by rmountjoy92** [comment]
This looks like something is set up incorrectly in your config.ini, does it work when using the default config:
`[Settings]
theme = light
accent = orange
background = None
roles = admin,user,public_user
home_access_groups = admin_only
settings_access_groups = admin_only
custom_app_title = DashMachine
sidebar_default = open

[admin]
role = admin
password = admin
confirm_password = admin`

**Comment by rmountjoy92** [comment]
I think this might be related to https://github.com/rmountjoy92/DashMachine/pull/67 reclone and see if it fixes it.

**Comment by nathanpalmer** [comment]
Must have been. I re-created my server and pulled in revision 6926b91896d33f9b59f36240d5ccc810aff3f0a6 and settings now shows up.
