### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dashmachine/dashmachine/user_data/auth_cache'

### ISSUE THREAD

**Issue by nathanpalmer** [rmountjoy92/DashMachine#70]
Fresh install on Ubuntu 19.04 pulled down git revision 6926b91896d33f9b59f36240d5ccc810aff3f0a6 (0.5) and it won't do anything until I create this directory. I checked out the code in `/opt/dashmachine`

```
Mar 28 21:35:51 dashboard gunicorn[13067]: Traceback (most recent call last):
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Mar 28 21:35:51 dashboard gunicorn[13067]:     worker.init_process()
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 119, in init_process
Mar 28 21:35:51 dashboard gunicorn[13067]:     self.load_wsgi()
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
Mar 28 21:35:51 dashboard gunicorn[13067]:     self.wsgi = self.app.wsgi()
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
Mar 28 21:35:51 dashboard gunicorn[13067]:     self.callable = self.load()
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
Mar 28 21:35:51 dashboard gunicorn[13067]:     return self.load_wsgiapp()
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
Mar 28 21:35:51 dashboard gunicorn[13067]:     return util.import_app(self.app_uri)
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 358, in import_app
Mar 28 21:35:51 dashboard gunicorn[13067]:     mod = importlib.import_module(module)
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Mar 28 21:35:51 dashboard gunicorn[13067]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/opt/dashmachine/wsgi.py", line 12, in <module>
Mar 28 21:35:51 dashboard gunicorn[13067]:     from dashmachine import app
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/opt/dashmachine/dashmachine/__init__.py", line 9, in <module>
Mar 28 21:35:51 dashboard gunicorn[13067]:     from dashmachine.paths import user_data_folder
Mar 28 21:35:51 dashboard gunicorn[13067]:   File "/opt/dashmachine/dashmachine/paths.py", line 25, in <module>
Mar 28 21:35:51 dashboard gunicorn[13067]:     os.mkdir(auth_cache)
Mar 28 21:35:51 dashboard gunicorn[13067]: FileNotFoundError: [Errno 2] No such file or directory: '/opt/dashmachine/dashmachine/user_data/auth_cache'
```

Once I create `/opt/dashmachine/dashmachine/user_data/auth_cache` everything works fine.

**Comment by rmountjoy92** [comment]
this was fixed in https://github.com/rmountjoy92/DashMachine/commit/b2c2a6135d7c3bcb2001404bd5d8d3b606bd03c4

**Comment by nathanpalmer** [comment]
I'm on the revision past that. But it looks like the issue is the fix is put in `run.py` and I was starting the service using `/usr/local/bin/gunicorn --bind 0.0.0.0:5000 wsgi:app`. I switched it back to use `run.py`. 

Thanks!
